### ISSUE TITLE
Rename repository project-pacific.oyster-seed-2015

### ISSUE THREAD

**Issue by Ellior2** [RobertsLab/project-pacific.oyster-larvae#10]
Is it possible to rename this repository **project-pacific.oyster-seed-2015** since I will want to make another one for the 2016 experiment? It doesn't seem like I have the authority to do so because I don't have the settings tab.

**Comment by sr320** [comment]
No lets keep this high level - this repo will likely be larger than your experiments etc.

Also- at this point it might be simpler to work in you own lab notebook space and we can integrate later on.
thanks

**Comment by Ellior2** [comment]
Ok I was starting to get confused as to where to work- the course repo, the Roberts lab repo, or my lab notebook. I don't want a bunch of duplicated files everywhere. I'll just focus on my Jekyll-now..
