### ISSUE TITLE
Raw data from first MS run?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-pacific.oyster-larvae#12]
No rush - though I thought we would use this repo / issues to slowly go through taking raw data to finished.

Making sure things are organized, backed up,and all software works. 

Thus, first question: Where is the raw MS data from the first experiments (4 samples?)

**Comment by Ellior2** [comment]
Ok sounds good. All raw data from 2015 and 2016 is in Owl under my folder trochophora.
