### ISSUE TITLE
Microbial Samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-pacific.oyster-larvae#14]
I would like to go ahead and send microbial samples out ...
Do you have samples that correspond with all of these samples:
https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/Diagrams/September-2015-samples.txt

And in what format are they? And location?

**Comment by Ellior2** [comment]
Great! Actually the microbial samples are from the [2016 experiment](https://github.com/RobertsLab/project-pacific.oyster-larvae/wiki/2016-Oyster-Seed-experiment-23C-vs.-29C).

Should we just process samples from silos 2, 3, and 9 like we did for proteomics? It would be 21 filters for those 3 silos for 7 sampling days. We also have 2 filters (from 23C and 29C) for Day 1 before we introduced larvae to the system. This brings us to 23 filters total. Filters are in ziplocs in my styrofoam container in the middle -80C freezer. They are all labeled with the data and silo number.
