### ISSUE TITLE
Add readme.md to Skyline-example-files-ETS.sky directory

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/project-pacific.oyster-larvae#15]

**Comment by sr320** [comment]
Given questionable nature of pipelines and lack of documentation on current analyses, I am closing..

**Comment by Ellior2** [comment]
I have not been working on the 2015 DIA skyline stuff and I am not really sure what you mean by this issue. I have been focusing attention on DDA.

**Comment by Ellior2** [comment]
I don't really know what those are. I think they are @emmats files.

**Comment by sr320** [comment]
As I closed it (the issue) an hour ago - it no longer needs attention.
