### ISSUE TITLE
Obtain FASTA file needed for Skyline example

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/project-pacific.oyster-larvae#16]
Step 4 from the [/Skyline-example-files-ETS.sky/slides01.pdf](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/Skyline-example-files-ETS.sky/slides01.pdf) specifies copying/pasting from the proteome background FASTA file.

Need this file to test example Skyline pipeline.

**Comment by sr320** [comment]
Consider this could be different workflow- thus not worth time / effort

**Comment by kubu4** [comment]
Isn't this the workflow that is being followed to get .blib files to open in Skyline?

**Comment by sr320** [comment]
It is available to look at (but not confirmed degree of relevance) this was
for Rhonda.

**Comment by kubu4** [comment]
Ok.
