### ISSUE TITLE
Discrepancy in 2016 experiment description

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-pacific.oyster-larvae#17]
It is not clear which silos were at 23 and 29

Please update wiki page.

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/2016_Oyster_Seed_experiment_23C_vs__29C_·_RobertsLab_project-pacific_oyster-larvae_Wiki_1E82CD75.png" alt="2016_Oyster_Seed_experiment_23C_vs__29C_·_RobertsLab_project-pacific_oyster-larvae_Wiki_1E82CD75.png"/>

**Comment by Ellior2** [comment]
Updated. I apologize... the small writeup at the bottom was incorrect.
