### ISSUE TITLE
ID of Ciliate

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-pacific.oyster-larvae#19]
I believe the putative Ciliate has been identified?
What is the species, and what documentation, scientific papers are available?

**Comment by Ellior2** [comment]
The ciliate Ralph identified in our dying oyster seed belongs to the Family Orchitophryidae (formerly Family Paranophryidae) but he says it's challenging to identify down to genus. I'll email you a PDF report from Ralph of the analysis that he did from our 2015 trials. 

He documents the ciliate in this paper. 

Elston et. al 1999.

http://www.sciencedirect.com.offcampus.lib.washington.edu/science/article/pii/S0044848698005122

**Comment by sr320** [comment]
Invasive orchitophryid ciliate infections in juvenile Pacific and Kumomoto oysters, Crassostrea gigas and Crassostrea sikamea


[1-s2.0-S0044848698005122-main.pdf](https://github.com/RobertsLab/project-pacific.oyster-larvae/files/866236/1-s2.0-S0044848698005122-main.pdf)
