### ISSUE TITLE
How much larvae to use?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-pacific.oyster-larvae#3]
How much…. When we had talked about larvae, the consensus was to sample 10K larvae twice everyother day. Is the number of individuals sampled relevant or are we just looking for a certain amount of biological material necessary to perform the proteomic analyses? From my last correspondence with Emma, it sounded like we just need 1 ug/ul. If I were to just collect let’s say 1ml of seed everyother day, does it matter that I would be probably be sampling 3K oysters on day 5 post-set but only about 100 oysters on day 14 for the 29C treatment? If we are just looking at the relative abundances of proteins within a group and not trying to quantify amount of a certain protein per oyster than perhaps it doesn’t matter? If we have 1L of seed per silo towards the end of the experiment and I am taking 1ml of seed, is that still a representative sample of our group?

**Comment by sr320** [comment]
Yes different numbers are fine but it is important to document. also note Emma's # probably refers to ug of extracted protein...

**Comment by emmats** [comment]
Yes, I am referring to ug of extracted protein.  You definitely need to start with more larvae than the end protein concentration you want.  We get rid of the shells (which are a lot of their mass) and then there is inevitable loss in the extraction process.  And 1 ug/ul is a minimum, it's always nicer and safer to have a higher concentration of protein to play with.

**Comment by Ellior2** [comment]
Ok, yes that is what I understood as well: 1ug/ul of extracted protein. I was trying to estimate what that might be in terms of actual larval volume or weight. Should I just try and take a certain weight or volume per sample, regardless of age and size? Either 1 ml or say 1 gram? My next question comes back to the size variation between treatments. If we want to compare the same size oysters between treatments- even though it may be a different day, this requires screening everyother day. So everyother day I could be potentially be taking two-1ml samples of seed per size class per treatment?

**Comment by emmats** [comment]
Taking a certain weight or volume sounds like a good plan.  1 ml of biological material would be much more than we need, but it never hurts to have extra.  Steven will have to jump in on the other response.

**Comment by Ellior2** [comment]
And if this is the case, I think I will need to be prepared with 500 of the 1.8 ml Nunc cryotubes that I had used for last year's experiment. I would anticipate using anywhere from 2-14 tubes per each of the 10 conicals per sample day. From Sigma it looks like it'll cost about $450 for 500. Or do you guys know of a cheaper alternative? And is this out of our budget or covered in the grant?

**Comment by sr320** [comment]
@Ellior2 
We should be able to provide tubes- Can you please draft a full protocol?

**Comment by kubu4** [comment]
I'm not sure of the full scope of this project, but thought I'd throw the following out there to think about:

Since a full set of protocols is being written for this projects, a mock statistical analysis should also probably be run to help determine sample/replicate numbers. The pre-experimental stats workup will help guide how sampling should be conducted.
