### ISSUE TITLE
Size Variation between treatments

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-pacific.oyster-larvae#4]
On to size variation between treatments… Because we are setting oysters at two different temperatures, we expect to see differences in settlement and growth rates. Let’s say I am going to sample two days after I initially put the larvae in the system to set. Do I sample the larvae that have set on the microculch, the larvae swimming, or try to homogenize the group by draining the water and sampling?

Let’s say we are screening at our normal screening day which is Day 5. From my experience, we will likely be harvesting seed holding mostly on a 450 micron screen for the 23C treatment and mostly 710s and 1000s for the 29C treatment. Let’s say we homogenize each silo of oyster seed to sample as we have done in the past. When we try to compare the proteins expressed in the 29C versus the 23C at Day 5, we will be comparing oysters in different stages of development due to their different growth rates in each treatment. Therefore when we see differences in protein expression between treatments- is it because they are growing at a different temperature or because they are developmentally in different stages? Should we be sampling oysters of certain sizes and trying to compare them to the same size in the other treatment, albeit it is a different day with different water chemistry and fluctuating food composition/quality?

**Comment by sr320** [comment]
All good questions- a better approach to this is to completely design experiment with diagrams. This should be a complete protocol to follow- and could be reproduced by anyone.
Please do this in the wiki feature.

**Comment by emmats** [comment]
I think we definitely want to try to compare oysters within the same stage.  I think it was in the Stumpp paper on gene expression in urchins that they found a stronger effect from developmental stage than treatment on gene expression.  But if you don't know that you are comparing different dev stages, you could be incorrectly assigning differences to treatment.

**Comment by sr320** [comment]
It will be important to identify developmental stage. My take is that this would be roughly accomplished with the different sieve size samples?  Maybe it would also be good to preserve some for microscopy.
