### ISSUE TITLE
Define and describe sampling events

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-pacific.oyster-larvae#8]
I believe there are two sampling events. Lets be sure to fully document procedure and sample status.

**Comment by Ellior2** [comment]
We actually have collected samples for proteomics for three experiments so far:
1) Oyster seed from September 2015: 29C vs 23C. Peptides have been isolated, MS/MS completed, and Emma just began looking at the data?
2) Geoduck larvae were exposed to low, medium and high PCO2 levels in April 2016. Samples are stored in -80C freezer at the Taylor Shellfish Hatchery and will be transferred to UW on 9/21/16.
3) Oyster seed from July 2016: 29C vs 23C (We also collected samples to study microbiomes, morphology, and histology). Samples are also in Taylor Shellfish -80C freezer and will also be transferred to UW on 9/21/16.

Full procedures to follow...

**Comment by kubu4** [comment]
Add sampling dates and links to spreadsheets/datasheets to [wiki](https://github.com/RobertsLab/project-pacific.oyster-larvae/wiki).

**Comment by sr320** [comment]
Thanks for getting two of these experiments up on the wiki- 
Could you add a bit of description of the experimental design (enough were someone else could recreate)?

Also where will you the geoduck trial design be placed?. - your notebook is of course fine.
