### ISSUE TITLE
Fork repository or edit RobertsLab repository?

### ISSUE THREAD

**Issue by Ellior2** [RobertsLab/project-pacific.oyster-larvae#9]
@sr320 @kubu4 I wasn't sure how to edit the existing wiki in repository RobertsLab/project-pacific.oyster-larvae so I decided to fork it. Do I need to be added as a collaborator to edit yours or should I just continue what I am doing and we can pull request later?

**Comment by sr320** [comment]
I will make you a collaborator. So that you can directly at it.

**Comment by kubu4** [comment]
I've added @Ellior2 as a collaborator.

**Comment by sr320** [comment]
Thanks! - I also added @Ellior2 at the Organization level so should have write access to all repos
